export type Game = {
  title: string
  provider: string
  badge?: "hot" | "drops"
  query: string
  image?: string
}

export const GAMES: Game[] = [
  { title: "The Dog House", provider: "Pragmatic Play", badge: "hot", query: "slot game cover the dog house cartoon dogs neon", image: "/games/dog-house.jpg" },
  { title: "Le Fisherman", provider: "Hacksaw", badge: "hot", query: "slot game cover raccoon fisherman cartoon", image: "/games/le-fisherman.jpg" },
  { title: "Minotaur", provider: "Endorphina", badge: "hot", query: "slot game cover greek minotaur dark mythology", image: "/games/minotaur.jpg" },
  { title: "Highway To Hell", provider: "NolimitCity", badge: "hot", query: "slot game cover highway to hell flames biker", image: "/games/highway-to-hell.jpg" },
  { title: "Ice Bass", provider: "Belatra", query: "slot game cover ice fishing fisherman bass cartoon", image: "/games/ice-bass.jpg" },
  { title: "Gates of Olympus", provider: "Pragmatic Play", query: "slot game cover gates of olympus zeus golden", image: "/games/gates-of-olympus.jpg" },
  { title: "Lady Wolf Moon", provider: "Bgaming", badge: "hot", query: "slot game cover lady wolf moon megaways neon", image: "/games/lady-wolf-moon.jpg" },
  { title: "Wild West Gold", provider: "Pragmatic Play", badge: "drops", query: "slot game cover wild west cowboy gold revolver", image: "/games/wild-west-gold.jpg" },
  { title: "MummyLand Treasures", provider: "Belatra", badge: "hot", query: "slot game cover mummy egypt treasures purple" },
  { title: "Flight Mode", provider: "NolimitCity", badge: "hot", query: "slot game cover airplane flight mode cartoon" },
  { title: "Sugar Rush Super", provider: "Pragmatic Play", badge: "hot", query: "slot game cover sugar rush candy pink" },
  { title: "Nazar Wishes", provider: "Endorphina", query: "slot game cover gypsy fortune teller crystal ball" },
  { title: "Cyber Gypsies", provider: "Belatra", query: "slot game cover cyber gypsies neon money cash" },
  { title: "Kiss My Chainsaw", provider: "NolimitCity", query: "slot game cover horror chainsaw neon couple" },
  { title: "Sweet Bonanza", provider: "Pragmatic Play", badge: "drops", query: "slot game cover sweet bonanza candy fruits pink" },
  { title: "Chaos Crew 2", provider: "Hacksaw", badge: "hot", query: "slot game cover chaos crew skulls graffiti" },
  { title: "Seamen", provider: "NolimitCity", query: "slot game cover sailors cartoon sea ocean" },
  { title: "Princess Suki", provider: "Belatra", query: "slot game cover japanese princess geisha pink" },
  { title: "Dork Unit", provider: "Hacksaw", query: "slot game cover dork unit cartoon comic" },
  { title: "Fortune of Giza", provider: "Pragmatic Play", query: "slot game cover egypt pharaoh gold pyramid" },
  { title: "Ze Zeus", provider: "Hacksaw", query: "slot game cover zeus thunder cartoon blue" },
  { title: "Voodoo Coins", provider: "Belatra", query: "slot game cover voodoo skull green coins" },
  { title: "Starlight Princess", provider: "Pragmatic Play", badge: "hot", query: "slot game cover starlight princess anime stars" },
  { title: "Le King", provider: "Hacksaw", query: "slot game cover king raccoon crown cartoon" },
  { title: "Crown Coins", provider: "Endorphina", query: "slot game cover crown gold coins red" },
  { title: "Home Of The Brave", provider: "NolimitCity", query: "slot game cover americana brave eagle stars" },
  { title: "2026 Hit Slot", provider: "Endorphina", query: "slot game cover hit slot 2026 gold gems" },
  { title: "Long Neck Fortune", provider: "Belatra", query: "slot game cover ostrich long neck cartoon money" },
  { title: "Eternal Duel", provider: "Hacksaw", query: "slot game cover eternal duel angel devil clouds" },
  { title: "Aztec Clusters", provider: "Bgaming", query: "slot game cover aztec clusters gold mayan" },
  { title: "The Crypt 2", provider: "NolimitCity", query: "slot game cover crypt horror gothic dark" },
  { title: "CULT.", provider: "Pragmatic Play", badge: "hot", query: "slot game cover cult dark mysterious people" },
  { title: "Dr. Jekyll & Mr. Hyde 2", provider: "Betsoft", query: "slot game cover jekyll hyde gothic potion" },
  { title: "Moneyfest", provider: "Popiplay", query: "slot game cover moneyfest piggy coins gold" },
  { title: "Mental", provider: "NolimitCity", query: "slot game cover mental asylum horror dark" },
  { title: "SCRATCH THE BANK", provider: "Mascot", query: "slot game cover cats robbery bank cartoon" },
  { title: "Riot: Urban Wilds", provider: "Mascot", query: "slot game cover riot urban wilds graffiti" },
  { title: "Charm Of The Dragon", provider: "Hacksaw", query: "slot game cover dragon charm asian green" },
  { title: "Crazy Ex-Girlfriend", provider: "NolimitCity", query: "slot game cover crazy girlfriend cartoon pink" },
  { title: "3 Royal Dracos", provider: "Endorphina", query: "slot game cover royal dragons crown red" },
  { title: "DRAGON'S BONANZA", provider: "Belatra", query: "slot game cover dragon bonanza red asian" },
  { title: "Gemhalla", provider: "Bgaming", badge: "hot", query: "slot game cover viking gems valhalla cartoon" },
  { title: "Raptor 2", provider: "Yggdrasil", query: "slot game cover raptor dinosaur jungle green" },
  { title: "Sugar Rush", provider: "Pragmatic Play", badge: "drops", query: "slot game cover sugar rush easter eggs candy" },
  { title: "Coins Of Leprechaun", provider: "Betsoft", query: "slot game cover leprechaun gold coins green" },
  { title: "Zeus the Invincible", provider: "Mascot", query: "slot game cover zeus invincible thunder god" },
  { title: "TacoHell", provider: "Popiplay", query: "slot game cover taco chef mexican food" },
  { title: "The Epic Win x125", provider: "Mascot", query: "slot game cover epic win 7 watermelon red" },
  { title: "Richy Hog", provider: "Belatra", query: "slot game cover rich pig money cartoon" },
  { title: "Bonanza Billion", provider: "Bgaming", query: "slot game cover bonanza billion candy yellow" },
  { title: "Kenneth Must Die", provider: "NolimitCity", query: "slot game cover kenneth office mafia" },
  { title: "Jackpot Pagoda", provider: "Belatra", query: "slot game cover jackpot pagoda asian gold" },
  { title: "Zeus vs Hades", provider: "Pragmatic Play", query: "slot game cover zeus vs hades gods war" },
  { title: "Deal With Death", provider: "Hacksaw", query: "slot game cover deal with death reaper red" },
  { title: "Dogmasons Mega Woof", provider: "Popiplay", query: "slot game cover dogs egypt mega woof gold" },
  { title: "A Big Catch", provider: "Betsoft", query: "slot game cover shark fishing big catch ocean" },
]
